### PR TITLE
Updated Vista theme

### PR DESCRIPTION
**Pull request by Haitch-1**
- Removed the segoe ui font because it broke system tray icons such as the network icon
- Updated screenshot to reflect how it actually looks now

I noticed a small problem though and I'm unsure on how to fix it: If you have multiple windows open, you can't tell that you actually have multiple windows open in the taskbar, if anyone could fix that then I'd be grateful.

### CODE REVIEW

**Comment by bbmaster123** [comment]
@Haitch-1 hey, so there was an update last night just before you posted this pull request. it fixed the font issue, glyphs are good now

Going to see as well if we can get pinned apps to not have a border/background if possible. Do you like the borders (There's actually 2, an inner and an outer) or did you prefer without?

As for multiple windows grouped, the target should be `Border#MultiWindowElement`
Happy to add that in and make the windows behind a bit darker than the front!

**Comment by Haitch-1** [comment]
I actually preferred the version I submitted originally however I do see what you're going for. Mine was more like a "modernized Vista" at first with the indicators included.


> Going to see as well if we can get pinned apps to not have a border/background if possible. Do you like the borders (There's actually 2, an inner and an outer) or did you prefer without?

I like the way it is now, however didn't my original have the pinned unopen apps un-bordered?

> As for multiple windows grouped, the target should be Border#MultiWindowElement
Happy to add that in and make the windows behind a bit darker than the front!

Yes please!

And thank you for improving my theme, I really don't know what I am doing when it comes to code!

**Comment by bbmaster123** [comment]
@Haitch-1 so you would prefer indicators be added back?
Yes they were un bordered before, I'm having trouble getting them to behave separately from running apps so at the moment anyway, its looking like all get the border or none get it. your call!

I added in the multiwindow style in my test version, which do you prefer, a dark gray color to show grouped icons, or system accent color? or a different color? again your call! :)

**Comment by Haitch-1** [comment]
The indicators might be necessary if all apps would have a border just to differentiate easier what you've got open in the background. It's basically a necessary evil to us, for example take a look at this screenshot:
image
Edge is the only unopened app and you can't tell :(

(Out of curiousity I tried the WinXP theme and it seems like it has this problem fixed, it seems like it actually utilizes the indicators as background borders, so maybe this'll work?)

 An accent color for grouped apps would look unnatural in my opinion, the dark gray shall do!
(Thanks again!)

**Comment by bbmaster123** [comment]
no worries I can add the indicators back in.

WinXP uses png images to get around the issue, which are hosted on imgur
I didn't want to mess with your theme too much initially, just wanted to add minor improvements not remake the whole thing
We can go for this if you want but then I'll need more time to work on it

If you do want to use pngs, then the indicators would also not be necessary either, although we can still have them

and sure thing, dark gray it is then!

**Comment by m417z** [comment]
> WinXP uses png images to get around the issue, which are hosted on imgur

I wasn't following the whole discussion, but regarding this, WinXP only uses png for the start button.

**Comment by Haitch-1** [comment]
It would be really nice if the theme actually looked closer to vista than my original creation, take as much time as you need :)

**Comment by bbmaster123** [comment]
ah yes I see
still, the WinXP theme only had to contend with the single border

I've removed the lighter outer border and some minor tweaking, and it respects the intended pinned apps style correctly now. It just doesn't looks as accurate on the other buttons. nbd, sometimes we have to strike a balance which can mean making a sacrifice somewhere. 

We can always switch this to pngs later if someone can provide all the resources needed ie start orb, button outlines, maybe glyph icons, etc

I also added the blur back in as it seems stable build now has the BackgroundControl target I had mentioned, check it out and if its good lets merge :)

**Comment by Haitch-1** [comment]
Looks good! However, I missed that active apps are actually supposed to have the darker background and the background ones are supposed to be light, oops!

I've looked around for the vista taskbar elements and I found a valuable resource in the [RetroBar](https://github.com/dremin/RetroBar) project in [Windows Vista Aero](https://github.com/dremin/RetroBar/blob/master/RetroBar/Themes/Windows%20Vista%20Aero.xaml) with the exact taskbar colors! 

Oh, and I also wanted to mention that a simple blue overlay on mouse hover would make it feel more like vista, I've tried tinkering around with it but I could not get my gradient to look good :/

**Pull request merged**
