### PR TITLE
FloatBar

### PR DESCRIPTION
**Pull request by AsvnDG**
add a new theme

### CODE REVIEW

**Comment by m417z** [comment]
From a quick glance at the screenshot, it looks very similar to Squircle. What are the substantial differences? I think we'd rather not have similar themes to have it easier for users to select a theme and not get lost among a large amount of similar options.

**Comment by AsvnDG** [comment]
Hi, thank you for checking

there are 2 different thing:
1. Split the SystemTrayFrame into segment
2. Now user can utilize "separator" on TaskbarFrame and able to "group" each pinned icon together using TaskSeparator11 app

example: 
user want to categorize app A,B,C as group 1 and app D,E,F into group 2

in Squircle theme each app is separated from another

and if the merge is approved lets change the name to SplitBar instead

**Comment by bbmaster123** [comment]
sorry, had been very busy this morning, windows live mail was acting up on boss's pc!

I'm inclined to agree with Michael, that this is very visually similar to Squircle. I do like the idea of being able to group your apps together along with taskseparator11, but not supporting transparency seems like it might be a kind of a big deal for some.

Maybe this could be a variant of squircle and the readme's merged?

**Comment by AsvnDG** [comment]
Hi, Thanks again

I still don't know how to support transparency without showing the darker color between icon (since it is overlapped)
it is fine either new theme or new variant

about drawing the seperators without TaskSeparator11, will it looks like this when rearrange ?
SplitBar

**Comment by AsvnDG** [comment]
Hi,
Sorry for very late reply.

You may disregard this PR, since I don't have any time to check the code.
but feel free to include it in Theme if you think it is good enough (transparent and sharp corner).

I'm closing this now and Thank you.

Cheers.

**Pull request closed without merging**
