### PR TITLE
Add Lucent theme

### PR DESCRIPTION
**Pull request by twistthoseknobs**
Contributing a theme that uses accent color.

### CODE REVIEW

**Comment by m417z** [comment]
Thanks. Please update the main readme file as well.

**Comment by twistthoseknobs** [comment]
Updated :)

**Comment by bbmaster123** [comment]
@twistthoseknobs 
Thanks for the submission!

What do you mean by "Browser"?

> ## Modifications
> **Browser getting too wide!** Adjust the _MaxWidth_ value, or remove it.

all else looks good to go :)

**Comment by twistthoseknobs** [comment]
Probably didn't word that right; I've set the tasklist button MaxWidth to 450 which can make a browser tab really wide. I don't mind it but just thought someone might have a problem with it:
image

**Comment by bbmaster123** [comment]
ah okay, in that case just to avoid confusion, how about wording it like

## Modifications
**Adjust Running Apps Button Width** - If the text of an app's button is very long, it can result in an unnecessarily wide button
image

To remedy this behavior:
- adjust the `MaxWidth` value to restrict the button's width to a preferred maximum value
- Remove `MaxWidth` to use Windows' default behavior
- Remove `MaxWidth` and set `Width` to set an identical static width to every running app

what do you think?

**Comment by twistthoseknobs** [comment]
Yes, that's a lot clearer. I don't know about the bullet point as I haven't used Width before, but if it's works that's all good.

**Comment by m417z** [comment]
Some feedback from Discord:

> Using the Windhawk  "Windows 11 Taskbar Styler" mod and the "Lucent (Light Bar)" theme it's hard to see the contents of my systray because of the background transparency.
> 
> Can I get help on how to change the background color of the systray from semi-transparent gradient to opaque black?
> 
> image

Perhaps it'd be a good idea to make it less transparent, what do you think?

**Comment by twistthoseknobs** [comment]
Yea can do. I've made a few adjustments on my end over time as well, I'll
make an update

**Comment by twistthoseknobs** [comment]
Made update to tray opacity and set a decent value for 'MaxWidth', is it ok if I remove the section referring to it in the readme and just work with the current value? (250)

**Comment by m417z** [comment]
In my opinion, a theme shouldn't set any MaxWidth value (unless there's a good reason for it, e.g. mimicking another Windows version). A user which prefers another value can adjust it manually or use the Taskbar Labels mod.

**Comment by twistthoseknobs** [comment]
Okay that's fair, can remove it completely.

**Pull request merged**
