### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AsvnDG**
Just updating to current design, need widget to be added to taskbar or else the icon will overlap

### CODE REVIEW

**Comment by bbmaster123** [comment]
ofc it does,
thaaaanks microsoft!

you see, if you happen to have your weather widget on the right side, the icons look fine. Even though it looks correct if its on the left, your code looks like this when its on the right:
image

and now you report the opposite is also true, when weather is on the left, the icons overlap. 

I've gone ahead and attempted to merge your update with what I have, so that it _SHOULD_ look correct both ways now.
can you give this a try and let me know? If so I'll clean up the ordering and put it through!
If not, we may need to have a variant for those with the weather on the other side...
```
{
  "controlStyles[0].target": "Rectangle#BackgroundFill",
  "controlStyles[0].styles[0]": "Fill=Transparent",
  "controlStyles[1].target": "Taskbar.TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement",
  "controlStyles[1].styles[0]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[1].styles[1]": "CornerRadius=5",
  "controlStyles[1].styles[2]": "Background@NoRunningIndicator:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.15\" />",
  "controlStyles[2].target": "Taskbar.TaskListButtonPanel > Border#BackgroundElement@CommonStates",
  "controlStyles[2].styles[0]": "CornerRadius=5",
  "controlStyles[2].styles[1]": "Background@ActivePointerOver=#B4202020",
  "controlStyles[2].styles[2]": "Background@InactivePointerOver=#B4202020",
  "controlStyles[2].styles[3]": "Background@ActivePressed=#B4101010",
  "controlStyles[2].styles[4]": "Background@InactivePressed=#B4101010",
  "controlStyles[2].styles[5]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[3].target": "Grid#SystemTrayFrameGrid",
  "controlStyles[3].styles[0]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[3].styles[1]": "CornerRadius=5",
  "controlStyles[3].styles[2]": "Margin=0,5,14,5",
  "controlStyles[3].styles[3]": "Padding=10,0,0,0",
  "controlStyles[4].target": "Taskbar.TaskListLabeledButtonPanel@CommonStates > Rectangle#RunningIndicator",
  "controlStyles[4].styles[0]": "Width=Auto",
  "controlStyles[4].styles[1]": "Height=39",
  "controlStyles[4].styles[2]": "Stroke@InactivePointerOver=#75A8E6",
  "controlStyles[4].styles[3]": "Stroke@InactivePressed=#7CB1F2",
  "controlStyles[4].styles[4]": "Stroke@ActiveNormal=#5F87B9",
  "controlStyles[4].styles[5]": "Stroke@ActivePointerOver=#75A8E6",
  "controlStyles[4].styles[6]": "Stroke@ActivePressed=#7CB1F2",
  "controlStyles[4].styles[7]": "Fill=Transparent",
  "controlStyles[4].styles[8]": "RadiusX=5",
  "controlStyles[4].styles[9]": "RadiusY=5",
  "controlStyles[4].styles[10]": "StrokeThickness=3",
  "controlStyles[5].target": "Taskbar.TaskListLabeledButtonPanel > TextBlock#LabelControl",
  "controlStyles[5].styles[0]": "Margin=4,0,0,0",
  "controlStyles[6].target": "Taskbar.SearchBoxButton",
  "controlStyles[6].styles[0]": "Margin=0,-4,0,-4",
  "controlStyles[7].target": "TextBlock#SearchBoxTextBlock",
  "controlStyles[7].styles[0]": "FontSize=12",
  "controlStyles[8].target": "Rectangle#BackgroundStroke",
  "controlStyles[8].styles[0]": "Visibility=Collapsed",
  "controlStyles[9].target": "Grid",
  "controlStyles[9].styles[0]": "RequestedTheme=2",
  "controlStyles[10].target": "Windows.UI.Xaml.Controls.Grid#DynamicSearchBoxGleamContainer",
  "controlStyles[10].styles[0]": "Margin=6",
  "controlStyles[11].target": "Taskbar.TaskListButton#TaskListButton[AutomationProperties.Name=Copilot] > Taskbar.TaskListLabeledButtonPanel#IconPanel > Border#BackgroundElement",
  "controlStyles[11].styles[0]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[12].target": "Border#BackgroundBorder",
  "controlStyles[12].styles[0]": "Margin=0,3,0,3",
  "controlStyles[12].styles[1]": "CornerRadius=5",
  "controlStyles[13].target": "Taskbar.TaskListButton#TaskListButton > Taskbar.TaskListLabeledButtonPanel#IconPanel@CommonStates > Border#BackgroundElement",
  "controlStyles[13].styles[0]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.2\" />",
  "controlStyles[13].styles[1]": "Background@InactivePointerOver:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[13].styles[2]": "Background@ActivePointerOver:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[14].target": "Taskbar.AugmentedEntryPointButton#AugmentedEntryPointButton > Taskbar.TaskListButtonPanel#ExperienceToggleButtonRootPanel > Border#BackgroundElement@CommonStates",
  "controlStyles[14].styles[0]": "Background@InactivePointerOver:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0\" />",
  "controlStyles[14].styles[1]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[15].target": "Border#MultiWindowElement",
  "controlStyles[15].styles[0]": "Background:=<AcrylicBrush TintColor=\"Black\" TintOpacity=\"0.8\" />",
  "controlStyles[16].target": "TextBlock#TimeInnerTextBlock",
  "controlStyles[16].styles[0]": "Foreground=White",
  "controlStyles[17].target": "TextBlock#DateInnerTextBlock",
  "controlStyles[17].styles[0]": "Foreground=White",
  "controlStyles[18].target": "SystemTray.TextIconContent > Grid > SystemTray.AdaptiveTextBlock#Base > TextBlock",
  "controlStyles[18].styles[0]": "Foreground=White",
  "controlStyles[5].styles[1]": "Foreground=White",
  "controlStyles[6].styles[1]": "Foreground=White",
  "controlStyles[7].styles[1]": "//Foreground=White"
}
```

**Comment by AsvnDG** [comment]
Hello,

A. My intention of the updated design is to integrate Start button, Search, Task View and Weather widget into 1 rectangular shape by editing its margin
Screenshot 2024-07-01 111022

but I face some problems:
1. If Search button is using other than Icon Only it will make longer rectangular and idk how to make the button fit into the design, hence I only use Icon Only
Screenshot 2024-07-01 110521
Screenshot 2024-07-01 110530



2. If I put Task View, the Weather button rectangle will have slightly different color (more transparent), hence I only use 3 button (Start, Search (Icon Only) and Weather)
Screenshot 2024-07-01 110600


3. If I exclude Weather (which it will only Start, Search) the next icon will overlap the Search button if that is not running (if the program is running it is still overlapped but since the color is pretty similar, it kind of OK if not looking at it directly)
Screenshot 2024-07-01 110941
Screenshot 2024-07-01 110919


B. Next what I want is to make running program (focused or not and have mouse cursor pointed to them) to have blur and dark color without border indicator
but I too face some problem:
1. The focused and/or cursor pointed program will have slightly darker color compared to non focused
Screenshot 2024-07-01 111550


By using the code that you provide it looks like this:
A. For Start, Search, Weather:
Screenshot 2024-07-01 105540
Screenshot 2024-07-01 105553
Screenshot 2024-07-01 105602


B. Running Program:
1. Focuses, will have blue border around its rectangle and the color is not dark
2. Not focuses, the color is not dark
Screenshot 2024-07-01 105701

3. Cursor pointed program will have dark color and blur border
Screenshot 2024-07-01 110258



I agree with you to have different variant
And I don't know how to swap Weather to right

**Comment by AsvnDG** [comment]
Hello,

I've check your config and found 1 minor issue with the size of the rectangle of running program, it looks smaller by 1px top and 1px bottom
1. Running and focused with pointer over
run focused pointer over


2. Running not focused without pointer over
run not focuses


The size is fine if:
1. Running and focused without pointer over
run focused


2. Run not focused with pointer over
run not focuses pointer over


Other than that it is Great
Thank you

**Comment by bbmaster123** [comment]
try adding: 
Taskbar.TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement
Margin=1

seems to fix it on my end, but I have to look really close on my screen, at 4k 1px is pretty hard to notice haha

**Comment by AsvnDG** [comment]
Fixed on my end too, it is perfect now

Thank you

**Comment by bbmaster123** [comment]
awesome! I'll push it through as soon as I have a chance :)

**Comment by AsvnDG** [comment]
Hi,
Sorry, I can't check it today and the next day (Thursday and Friday)

for wallpaper, I use "Field of Dreams" from [here](https://www.pantone.com/color-of-the-year/downloads/wallpaper)
fortunately I have backup the clock code

`{
  "ShowSeconds": 0,
  "TimeFormat": "HH':'mm'",
  "DateFormat": "ddd',' dd MMM yyyy",
  "WeekdayFormat": "dddd",
  "TopLine": "",
  "BottomLine": "%date% | %time%   ",
  "MiddleLine": "%weekday%",
  "TooltipLine": "%web1_full%",
  "Width": 180,
  "Height": 60,
  "TextSpacing": 1,
  "WebContentsItems[0].Url": "https://feeds.bbci.co.uk/news/world/rss.xml",
  "WebContentsItems[0].BlockStart": "<item>",
  "WebContentsItems[0].Start": "<title><![CDATA[",
  "WebContentsItems[0].End": "]]></title>",
  "WebContentsItems[0].MaxLength": 28,
  "WebContentsUpdateInterval": 10,
  "TimeStyle.Visible": 0,
  "TimeStyle.TextColor": "",
  "TimeStyle.TextAlignment": "",
  "TimeStyle.FontSize": 0,
  "TimeStyle.FontFamily": "",
  "TimeStyle.FontWeight": "",
  "TimeStyle.FontStyle": "",
  "TimeStyle.FontStretch": "",
  "TimeStyle.CharacterSpacing": 0,
  "DateStyle.TextColor": "",
  "DateStyle.TextAlignment": "",
  "DateStyle.FontSize": 12,
  "DateStyle.FontFamily": "",
  "DateStyle.FontWeight": "Normal",
  "DateStyle.FontStyle": "",
  "DateStyle.FontStretch": "",
  "DateStyle.CharacterSpacing": 0,
  "oldTaskbarOnWin11": 0
}`

**Review by bbmaster123 — APPROVED** [review]

**Comment by bbmaster123** [comment]
Thanks for the clock code and wallpaper!
I'm not the best at photoshop but I think the screenshots came out pretty well :)

going to push this through now, thanks again!

**Pull request merged**
